/*	AUTORES:	Isabela Telles				RA:	170012
				João Paulo Penalber				170556
				Leonardo de Oliveira Ramos		171941
*/
/* SELECTS PARA AVALIACAO */

/* NUMEROS DE BO DA CIRCUNSCRICAO '38º D.P. VILA AMALIA' */
SELECT B.ID_BO,
		B.ANO_BO,
		B.SOLUCAO,
        D.NOME AS NOME_DELEGACIA,
        D.CIRCUNSCRICAO
FROM BO B
	INNER JOIN DELEGACIA D
		ON D.NOME = B.D_NOME
WHERE D.CIRCUNSCRICAO = '38º D.P. VILA AMALIA'
ORDER BY B.ID_BO;

/*NUMERO DE OCORRENCIAS DE NOITE POR DELEGACIA */

SELECT BD.NOME AS NOME_DELEGACIA,
		COUNT(O.PERIODO_OCORRENCIA) AS NUM_OCORRENCIA_NOITE
FROM (SELECT B.ID_BO, D.NOME FROM BO B INNER JOIN DELEGACIA D ON B.D_NOME = D.NOME) BD 
		INNER JOIN OCORRENCIA O ON BD.ID_BO = BOLETIM_OCORRENCIA
WHERE O.PERIODO_OCORRENCIA = 'A NOITE' 
GROUP BY O.PERIODO_OCORRENCIA, BD.NOME;

/* LISTA DE OCORRENCIA COM ESPECIE(Ato infracional) EM S.PAULO ORDENADO PELA DATA DE INICIO DO BO*/

SELECT OB.ID_BO,
		OB.ANO_BO,
		OB.ESPECIE,
        E.CIDADE,
		OB.DATA_INICIADO AS BO_INICIADO
FROM (SELECT B.DATA_INICIADO, O.ESPECIE, O.ENDERECO_LATITUDE, O.ENDERECO_LONGITUDE, B.ID_BO, B.ANO_BO FROM OCORRENCIA O
		INNER JOIN BO B ON O.BOLETIM_OCORRENCIA = B.ID_BO) OB INNER JOIN ENDERECO E ON (OB.ENDERECO_LATITUDE = E.LATITUDE AND OB.ENDERECO_LONGITUDE = E.LONGITUDE)
WHERE E.CIDADE = 'S.PAULO' AND OB.ESPECIE = 'Ato infracional'
ORDER BY OB.DATA_INICIADO;

/* NUMERO DE OCORRENCIA COM ESPECIE(Título II - Patrimônio (arts. 155 a 183)) POR DELAGACIA EM S.PAULO*/

SELECT BDO.NOME AS NOME_DELEGACIA,
		E.CIDADE,
		COUNT(BDO.ESPECIE) AS NUM_ESPECIE
FROM (SELECT O.ENDERECO_LATITUDE, O.ENDERECO_LONGITUDE, BD.NOME, O.ESPECIE
			FROM(SELECT B.ID_BO, D.NOME 
						FROM BO B INNER JOIN DELEGACIA D ON B.D_NOME = D.NOME) BD 
		INNER JOIN OCORRENCIA O ON BD.ID_BO = BOLETIM_OCORRENCIA) BDO INNER JOIN ENDERECO E ON (BDO.ENDERECO_LATITUDE = E.LATITUDE AND BDO.ENDERECO_LONGITUDE = E.LONGITUDE)
WHERE E.CIDADE = 'S.PAULO' AND BDO.ESPECIE = 'Título II - Patrimônio (arts. 155 a 183)'
GROUP BY BDO.NOME, E.CIDADE, BDO.ESPECIE;

/* NUMERO DO BO E DATA_OCORRENCIA E ESPECIE DA OCCORRENCIA DA DELEGACIA 69º D.P. TEOTONIO VILELA */

SELECT B.ID_BO, ID_OCORRENCIA, O.DATA_COMUNICACAO, O.ESPECIE, RUBRICA, DESDOBRAMENTO , D.NOME
FROM BO B INNER JOIN OCORRENCIA O ON ID_BO = BOLETIM_OCORRENCIA
			INNER JOIN DELEGACIA D ON D.NOME = B.D_NOME
GROUP BY B.ID_BO, O.ID_OCORRENCIA HAVING D.NOME = "69º D.P. TEOTONIO VILELA" 
ORDER BY ID_BO;
